### ISSUE TITLE
Unable to build prod with Highlight module included

### ISSUE THREAD

**Issue by jfinci1** [Teradata/covalent#1139]
### Do you want to request a *feature* or report a *bug*?

Bug Report
#### Bug Report

```
ERROR in ./node_modules/highlight.js/lib/languages/maxima.js
Module build failed: RangeError: Maximum call stack size exceeded
    at Object.aggregateTransformFlags (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51904:37)
    at visitNode (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51052:12)
    at Object.visitEachChild (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
    at visitor (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/src/transforms/import-tslib.js:33:27)
    at visitNode (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51053:23)
    at Object.visitEachChild (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
    at visitor (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/src/transforms/import-tslib.js:33:27)
    at visitNode (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51053:23)
    at Object.visitEachChild (/Users/finci/Development/sales-eng/sapb1/fe/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
```

#### What is the expected behavior?

Ideally the prod build should succeed.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

```
dependencies": {
    "@angular/animations": "^5.2.8",
    "@angular/cdk": "^5.2.4",
    "@angular/cli": "^1.7.2",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.8",
    "@angular/core": "^5.2.8",
    "@angular/flex-layout": "^5.0.0-beta.13",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@covalent/core": "^1.0.0",
    "@covalent/highlight": "^1.0.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.6",
    "typescript": "^2.7.1",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^5.2.8",
    "@angular/language-service": "^5.2.0"
  }
```

**Comment by emoralesb05** [comment]
This issue happens because of the underlying lib of `highlight.js`.. the only solve i found for this was to upgrade to `node 8`.. which will be required when moving to angular 6 either way.

**Comment by jeremysmartt** [comment]
closing issue, upgrade node 8 as solution
