### ISSUE TITLE
Covalent text editor (latest v8) is not working with Angular 18

### ISSUE THREAD

**Issue by SankarPerumal25** [Teradata/covalent#2181]
I am upgrading my existing Angular application to latest version (v18.0.4), for that I am trying to use the latest covalent text editor (v8.14.1) in it. The editor is not working and showing the below error in browser console window. 

Error which I get in a brand new app,
```
ERROR TypeError: EasyMDE is not a constructor
    at _TdTextEditorComponent.ngAfterViewInit (covalent-text-editor.mjs:63:21)
    at callHookInternal (core.mjs:5151:14)
    at callHook (core.mjs:5178:13)
    at callHooks (core.mjs:5132:17)
    at executeInitAndCheckHooks (core.mjs:5082:9)
    at refreshView (core.mjs:13245:21)
    at detectChangesInView (core.mjs:13386:9)
    at detectChangesInViewIfAttached (core.mjs:13346:5)
    at detectChangesInComponent (core.mjs:13335:5)
    at detectChangesInChildComponents (core.mjs:13399:9)

```
Error which I get in the existing migrating angular app,
```
ERROR TypeError: hr is not a constructor
    at t.ngAfterViewInit (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:760767)
    at bT (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:370390)
    at x5 (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:370537)
    at vT (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:370295)
    at tv (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:370019)
    at d8 (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:405733)
    at rC (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:406301)
    at x1 (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:406123)
    at w1 (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:406055)
    at d8 (27dd1a80-4ee3-4e8a-82c3-786ccc8a074a:1:405229)

```
Kindly help on this.

**Comment by tsg-tthrash** [comment]
We have an existing app that was built with Covalent and is stuck on Angular 17 until Covalent is upgraded to support Angular 18 as well. This project has security requirements, so the vulnerability patches at a minimum are needed from Angular 18 (and Covalent). So, the sooner Covalent can be upgraded the better!

**Comment by owilliams320** [comment]
This should be working in the latest supported covalent now 10.x please check
