### ISSUE TITLE
WebAnimations not working as desired on all platforms.

### ISSUE THREAD

**Issue by ravinderpayal** [Teradata/covalent#517]
Working Fine on Firefox, Latest Chrome on Windows 7 but not on Windows 8  Chrome@Latest

Whenever I click a link in Nav-View, it renders the Component Linked with the link clicked, but thereafter freezes all events. And shows a long error in console:-

```
Unhandled Promise rejection: Cannot read property 'play' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'play' of undefined
    at WebAnimationsPlayer.play (browser.es5.js:2344)
    at _loop_2 (browser.es5.js:1621)
    at InjectableAnimationEngine.DomAnimationEngine._flushQueuedAnimations (browser.es5.js:1626)
    at InjectableAnimationEngine.DomAnimationEngine.flush (browser.es5.js:1647)
    at animations.es5.js:263
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invoke (zone.js:365)
    at Zone.webpackJsonp.974.Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invokeTask (zone.js:398)
    at Zone.webpackJsonp.974.Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464) TypeError: Cannot read property 'play' of undefined
    at WebAnimationsPlayer.play (http://192.168.43.229:4200/vendor.bundle.js:67941:21)
    at _loop_2 (http://192.168.43.229:4200/vendor.bundle.js:67218:24)
    at InjectableAnimationEngine.DomAnimationEngine._flushQueuedAnimations (http://192.168.43.229:4200/vendor.bundle.js:67223:27)
    at InjectableAnimationEngine.DomAnimationEngine.flush (http://192.168.43.229:4200/vendor.bundle.js:67244:14)
    at http://192.168.43.229:4200/vendor.bundle.js:113212:35
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invoke (http://192.168.43.229:4200/polyfills.bundle.js:2961:26)
    at Zone.webpackJsonp.974.Zone.run (http://192.168.43.229:4200/polyfills.bundle.js:2721:43)
    at http://192.168.43.229:4200/polyfills.bundle.js:3356:57
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invokeTask (http://192.168.43.229:4200/polyfills.bundle.js:2994:31)
    at Zone.webpackJsonp.974.Zone.runTask (http://192.168.43.229:4200/polyfills.bundle.js:2761:47)
    at drainMicroTaskQueue (http://192.168.43.229:4200/polyfills.bundle.js:3189:35)
    at HTMLAnchorElement.ZoneTask.invoke (http://192.168.43.229:4200/polyfills.bundle.js:3060:25)
consoleError @ zone.js:569
handleUnhandledRejection @ zone.js:574
_loop_1 @ zone.js:609
drainMicroTaskQueue @ zone.js:613
ZoneTask.invoke @ zone.js:464
zone.js:571 Error: Uncaught (in promise): TypeError: Cannot read property 'play' of undefined
TypeError: Cannot read property 'play' of undefined
    at WebAnimationsPlayer.play (browser.es5.js:2344)
    at _loop_2 (browser.es5.js:1621)
    at InjectableAnimationEngine.DomAnimationEngine._flushQueuedAnimations (browser.es5.js:1626)
    at InjectableAnimationEngine.DomAnimationEngine.flush (browser.es5.js:1647)
    at animations.es5.js:263
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invoke (zone.js:365)
    at Zone.webpackJsonp.974.Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invokeTask (zone.js:398)
    at Zone.webpackJsonp.974.Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464)
    at WebAnimationsPlayer.play (browser.es5.js:2344)
    at _loop_2 (browser.es5.js:1621)
    at InjectableAnimationEngine.DomAnimationEngine._flushQueuedAnimations (browser.es5.js:1626)
    at InjectableAnimationEngine.DomAnimationEngine.flush (browser.es5.js:1647)
    at animations.es5.js:263
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invoke (zone.js:365)
    at Zone.webpackJsonp.974.Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invokeTask (zone.js:398)
    at Zone.webpackJsonp.974.Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464)
    at resolvePromise (zone.js:712) [<root>]
    at :4200/polyfills.bundle.js:3359:17 [<root>]
    at Zone.webpackJsonp.974.Zone.runTask (zone.js:165) [<root> => <root>]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464) [<root>]
consoleError @ zone.js:571
handleUnhandledRejection @ zone.js:574
_loop_1 @ zone.js:609
drainMicroTaskQueue @ zone.js:613
ZoneTask.invoke @ zone.js:464
core.es5.js:1085 ERROR Error: Uncaught (in promise): NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
Error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer._triggerWebAnimation (browser.es5.js:2309)
    at WebAnimationsPlayer.init (browser.es5.js:2292)
    at InjectableAnimationEngine.DomAnimationEngine._queuePlayer (browser.es5.js:1584)
    at InjectableAnimationEngine.DomAnimationEngine.animateTransition (browser.es5.js:1498)
    at InjectableAnimationEngine.DomAnimationEngine.setProperty (browser.es5.js:1369)
    at AnimationRenderer.setProperty (animations.es5.js:226)
    at DebugRenderer2.setProperty (core.es5.js:13309)
    at setElementProperty (core.es5.js:9586)
    at checkAndUpdateElementValue (core.es5.js:9505)
    at checkAndUpdateElementInline (core.es5.js:9439)
    at checkAndUpdateNodeInline (core.es5.js:12130)
    at checkAndUpdateNode (core.es5.js:12105)
    at debugCheckAndUpdateNode (core.es5.js:12734)
    at debugCheckRenderNodeFn (core.es5.js:12713)
    at Object.eval [as updateRenderer] (MdTabBody.html:1)
    at WebAnimationsPlayer._triggerWebAnimation (browser.es5.js:2309)
    at WebAnimationsPlayer.init (browser.es5.js:2292)
    at InjectableAnimationEngine.DomAnimationEngine._queuePlayer (browser.es5.js:1584)
    at InjectableAnimationEngine.DomAnimationEngine.animateTransition (browser.es5.js:1498)
    at InjectableAnimationEngine.DomAnimationEngine.setProperty (browser.es5.js:1369)
    at AnimationRenderer.setProperty (animations.es5.js:226)
    at DebugRenderer2.setProperty (core.es5.js:13309)
    at setElementProperty (core.es5.js:9586)
    at checkAndUpdateElementValue (core.es5.js:9505)
    at checkAndUpdateElementInline (core.es5.js:9439)
    at checkAndUpdateNodeInline (core.es5.js:12130)
    at checkAndUpdateNode (core.es5.js:12105)
    at debugCheckAndUpdateNode (core.es5.js:12734)
    at debugCheckRenderNodeFn (core.es5.js:12713)
    at Object.eval [as updateRenderer] (MdTabBody.html:1)
    at resolvePromise (zone.js:712) [angular]
    at resolvePromise (zone.js:683) [angular]
    at :4200/polyfills.bundle.js:3356:17 [angular]
    at Object.onInvokeTask (core.es5.js:4136) [angular]
    at ZoneDelegate.webpackJsonp.974.ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.webpackJsonp.974.Zone.runTask (zone.js:165) [<root> => angular]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464) [<root>]
defaultErrorLogger @ core.es5.js:1085
ErrorHandler.handleError @ core.es5.js:1145
next @ core.es5.js:4774
schedulerFn @ core.es5.js:3848
SafeSubscriber.__tryOrUnsub @ Subscriber.js:236
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3834
NgZone.triggerError @ core.es5.js:4205
onHandleError @ core.es5.js:4166
webpackJsonp.974.ZoneDelegate.handleError @ zone.js:369
webpackJsonp.974.Zone.runGuarded @ zone.js:141
_loop_1 @ zone.js:604
drainMicroTaskQueue @ zone.js:613
ZoneTask.invoke @ zone.js:464
```

It's working fine earlier, and things started getting wrong after updating Covalent to 1.0.0-beta.3-2

**Comment by emoralesb05** [comment]
This seems more of an `@angular@4.0.0` issue. Which component gives you this error in particular?

**Comment by ravinderpayal** [comment]
I think it's `td-layout-nav`. The error comes just after the new route/view is rendered on route change.

**Comment by emoralesb05** [comment]
🤔  hmm, its weird since `td-layout-nav` doesnt contain any animations.. gonna dig into it a bit. If you have more information please let us know.

**Comment by ravinderpayal** [comment]
Not the td-layout-nav but slide panels and side navigation panels hide
their self on clicking a link (in the panel) and uses animation to do so.

**Comment by kyleledbetter** [comment]
Hmm that just using the angular material md-sidenav under the hood. Wonder if they've had this issue in their repo

**Comment by ravinderpayal** [comment]
Yeah, and understanding this console log is also tedious.

**Comment by ranouf** [comment]
Did you find a solution? 
I have the same problem

**Comment by jotatoledo** [comment]
@ranouf  or @ravinderpayal can any replicate the issue?

**Comment by emoralesb05** [comment]
Is this still an issue?

**Comment by jeremysmartt** [comment]
no traction on issue in 11 months, closing
