### ISSUE TITLE
TdToggleDirective: this._renderer.setStyle is not a function

### ISSUE THREAD

**Issue by paistipoikka** [Teradata/covalent#519]
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?

Bug

#### Bug Report

the component contains multiple TdToggle directives. When injecting the ngx translate service into the component I receive the following error:

```
Uncaught (in promise): TypeError: this._renderer.setStyle is not a function
TypeError: this._renderer.setStyle is not a function
    at TdToggleDirective.exports.TdToggleDirective.TdToggleDirective.show (http://localhost:63342/myapp/node_modules/@covalent/core/core.umd.js:95:24)
    at TdToggleDirective.set [as state] (http://localhost:63342/myapp/node_modules/@covalent/core/core.umd.js:44:22)
    at updateProp (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:10973:37)
    at checkAndUpdateDirectiveInline (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:10670:19)
    at checkAndUpdateNodeInline (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12091:17)
    at checkAndUpdateNode (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12059:16)
    at debugCheckAndUpdateNode (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12688:59)
    at debugCheckDirectivesFn (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12629:13)
    at Object.eval [as updateDirectives] (ng:///CalendarModule/CalendarDetailPage.ngfactory.js:176:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12614:21)
    at checkAndUpdateView (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12026:14)
    at callViewAction (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12341:17)
    at execEmbeddedViewsAction (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12313:17)
    at checkAndUpdateView (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12027:5)
    at callViewAction (http://localhost:63342/myapp/node_modules/@angular/core/bundles/core.umd.js:12341:17)
```

simply remove the injected ngx translate service from the constructor and the error disappears.

#### What is the expected behavior?

Simply injecting the service into the component without using it should make no difference. 

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular 4.1.0-rc.0
material 2.0.0-beta.3
Covalent v1.0.0-beta.3-1

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by paistipoikka** [comment]
Strange thing about this is that I injected another service in addition to the translate service and the problem disappeared.... seems like that's an angular problem....
