### ISSUE TITLE
Data table - Error when multipleRowSelect : boolean = true;

### ISSUE THREAD

**Issue by arunanamal** [Teradata/covalent#559]
Hi,
I got an error when I put multiple: boolean = true; (multiple row select)
If I make it to false then it works.
Error says
vendor.bundle.js:1295 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'find' of null
TypeError: Cannot read property 'find' of null
    at TdDataTableComponent.areAllSelected (http://localhost:4200/vendor.bundle.js:46050:31)
    at Object.View_TdDataTableComponent_2.currVal_0 [as updateDirectives] (ng:///CovalentDataTableModule/TdDataTableComponent.ngfactory.js:98:25)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:4200/vendor.bundle.js:12824:21)

Thank you...

**Comment by kyleledbetter** [comment]
I think I faced this. Try putting and ngIf on the data table for so it doesn't show before the data object loads

**Comment by emoralesb05** [comment]
This happens more than often, so we might need to set a validation for the `undefined` case
