### ISSUE TITLE
Error After upgrading to angular material beta 12.

### ISSUE THREAD

**Issue by gbrigens** [Teradata/covalent#929]
I am running into this error after upgrading to `"@angular/material": "^2.0.0-beta.12",` and `"@angular/cdk": "^2.0.0-beta.12",` what am I doing wrong?
```
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/search/search-input/search-input.component.d.ts (2,28): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'Dir'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/chips/chips.component.d.ts (4,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdChip'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/chips/chips.component.d.ts (4,36): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'TemplatePortalDirective'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/chips/chips.component.d.ts (4,61): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdOption'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/chips/chips.component.d.ts (4,71): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdAutocompleteTrigger'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/data-table/directives/data-table-template.directive.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'TemplatePortalDirective'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/dialogs/alert-dialog/alert-dialog.component.d.ts (1,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdDialogRef'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/dialogs/confirm-dialog/confirm-dialog.component.d.ts (1,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdDialogRef'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/dialogs/prompt-dialog/prompt-dialog.component.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdDialogRef'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/dialogs/services/dialog.service.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdDialog'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/dialogs/services/dialog.service.d.ts (2,20): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdDialogRef'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/dialogs/services/dialog.service.d.ts (2,33): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdDialogConfig'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/dialogs/services/dialog.service.d.ts (2,49): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'ComponentType'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/expansion-panel/expansion-panel.component.d.ts (3,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'TemplatePortalDirective'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/file/file-input/file-input.component.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'TemplatePortalDirective'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/json-formatter/json-formatter.component.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'Dir'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/layout/layout.component.d.ts (1,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenav'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/layout/layout.component.d.ts (1,21): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenavToggleResult'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/layout/layout-nav-list/layout-nav-list.component.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenav'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/layout/layout-nav-list/layout-nav-list.component.d.ts (2,21): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenavToggleResult'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/layout/layout-manage-list/layout-manage-list.component.d.ts (1,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenav'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/layout/layout-manage-list/layout-manage-list.component.d.ts (1,21): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenavToggleResult'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/layout/navigation-drawer/navigation-drawer.component.d.ts (4,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenavToggleResult'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/loading/loading.component.d.ts (3,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'TemplatePortal'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/loading/services/loading.factory.d.ts (3,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'Overlay'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/paging/paging-bar.component.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'Dir'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/search/search-input/search-input.component.d.ts (2,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdInputDirective'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/chips/chips.component.d.ts (4,18): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdInputDirective'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/steps/step.component.d.ts (3,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'TemplatePortalDirective'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@covalent/core/steps/step.component.d.ts (3,35): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'TemplatePortal'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (12,3): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdButtonModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (12,19): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdCardModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (12,33): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdIconModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (13,3): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdListModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (13,17): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdMenuModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (13,31): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdTooltipModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (14,3): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSlideToggleModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (14,24): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdInputModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (14,39): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdCheckboxModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (15,3): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdToolbarModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (15,20): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSnackBarModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (15,38): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSidenavModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (16,3): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdTabsModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/shared/shared.module.ts (16,17): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSelectModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (6,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSnackBarModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (6,28): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdIconModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (6,42): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdListModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (6,56): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdTooltipModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (6,73): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdCardModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (6,87): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdButtonModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (7,10): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdToolbarModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (7,27): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdInputModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (7,42): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdSlideToggleModule'.
ERROR in /Users/macbook/projects/Angular/Studio/dashboard/src/app/components/dashboard/categories/category.module.ts (7,63): Module '"/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/material/material"' has no exported member 'MdMenuModule'.
ERROR in Error: MdButtonModule is not an NgModule
    at _getNgModuleMetadata (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at /Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/macbook/projects/Angular/Studio/dashboard/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by aciccarello** [comment]
What version of covalent are you using? beta 8-1 is the first to support Material beta 12.

**Comment by gbrigens** [comment]
This is the one I have `covalent/core": "^1.0.0-beta.5"`

**Comment by aciccarello** [comment]
@gbrigens Covalent appears to be at version `1.0.0-beta.8`. You will need version `1.0.0-beta.8-1.

Run `npm install @covalent/core@1.0.0-beta.8-1` for each of the covalent modules

_A little github tip, use three backticks before and after your content to include code blocks with multiple lines._

**Comment by emoralesb05** [comment]
Closing since its stated in the changelog which covalent version supports which material version.
